gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2592000
    manager_type: orm
    single_use: true
    user_provider: db_users
    ttl_update: true
    cookie:
        enabled: true
        same_site: lax
        path: /
        domain: null
        http_only: false
        secure: false
        remove_token_from_body: true

# https://github.com/markitosgv/JWTRefreshTokenBundle
