gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: '%env(int:JWT_REFRESH_TOKEN_TTL)%'
    manager_type: orm
    single_use: true
    user_provider: db_users
    ttl_update: true
    cookie:
        enabled: true
        same_site: none
        path: /
        domain: null
        http_only: false
        secure: '%env(bool:JWT_REFRESH_COOKIE_SECURE)%'
        remove_token_from_body: true

# https://github.com/markitosgv/JWTRefreshTokenBundle
