version: '3.4'

services:
  php-fpm:
    image: ghcr.io/retch/shareabike-backend:latest
    environment:
      APP_ENV: prod
      # Choose a unique app secret
      APP_SECRET: 00000000000000000000000000000000
      DATABASE_URL: postgresql://app:app@db:5432/shareabike?serverVersion=15&charset=utf8
      JWT_TTL: 300
      JWT_REFRESH_COOKIE_SECURE: true
      JWT_REFRESH_TOKEN_TTL: 2592000
      # Adapter password hash $ has to be escaped with another $. The hashed password equals "password". Please change! https://bcyrpt.online
      ADAPTER_USERNAME: adapter
      ADAPTER_PASSWORDHASH: $$2y$$05$$FeOvneskMbZH6BomStPKp.h.cV035NSTFF66JJOmu.ox60DHt2Eeq
      CORS_ALLOW_ORIGIN: http://localhost:4200 # Change this to your frontend URL
    restart: unless-stopped
    command: sh -c "php bin/console cache:clear && php bin/console doctrine:migrations:migrate --no-interaction && php bin/console lexik:jwt:generate-keypair --skip-if-exists && php-fpm"
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "9000"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx:1.25.2-alpine3.18
    container_name: shareabike-backend-nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_DB: shareabike
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d shareabike"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - shareabike_db_data:/var/lib/postgresql/data
    ports:
      - "5420:5432"
  omni-adapter:
    image: ghcr.io/retch/shareabike-omni-lock-adapter:latest
    restart: unless-stopped
    environment:
      - BACKEND_HOST_URL=http://nginx:80
      - BACKEND_USERNAME=adapter
      - BACKEND_PASSWORD=password
    ports:
      - "9679:9679"
    depends_on:
      - nginx

volumes:
  shareabike_db_data:
