version: '3.4'

services:
  php-fpm:
    build:
      context: .
    environment:
      APP_ENV: dev
      # Choose a unique app secret
      APP_SECRET: 00000000000000000000000000000000
      DATABASE_URL: postgresql://app:app@db:5432/shareabike?serverVersion=15&charset=utf8
      # Adapter password hash $ has to be escaped with another $. The hashed password equals "password". Please change! https://bcyrpt.online
      ADAPTER_USERNAME: adapter
      ADAPTER_PASSWORDHASH: $$2y$$05$$CCeJCVyhcFXQl9WM.DbdzOzIrwQ13Ab7u75FO78f.XDKNkwu.XsAu
    restart: unless-stopped
    command: sh -c "php bin/console doctrine:migrations:migrate --no-interaction && php-fpm"
    healthcheck:
           test: ["CMD", "nc", "-zv", "localhost", "9000"]
           interval: 10s
           timeout: 5s
           retries: 5
    depends_on:
      db:
        condition: service_healthy
  nginx:
      image: nginx:1.25.2-alpine
      container_name: shareabike-backend
      ports:
          - "8000:80"
      volumes:
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
          - php-fpm
  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_DB: shareabike
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d shareabike"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - shareabike_db_data:/var/lib/postgresql/data
    ports:
      - "5420:5432"

volumes:
  shareabike_db_data:
